config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :invoices do
    collection do
      get :xhr_add_invoice
      post :xhr_add_invoice
    end
    member do
      get :xhr_change_client_name
      patch :xhr_change_client_name
    end
    resources :purchase_orders do
      collection do
        get :xhr_add_purchase_order
        post :xhr_add_purchase_order
      end
    end
  end

  root to: 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  validates :client_name, presence: true, uniqueness: true
  validates :amount, presence: true, numericality: { greater_than: 0 }

  def total
    if tax.present?
      amount * (1 + (tax / 100))
    else
      amount
    end
  end
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  enum status: %i[draft paid delivered].freeze

  belongs_to :invoice

  validates :client_name, :status, :vendor, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }

  default_scope -> { order('created_at desc') }

  def total
    if tax.present?
      amount * (1 + (tax / 100))
    else
      amount
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :find_invoice, only: %w[destroy xhr_change_client_name]

  def index
    @invoices = Invoice.all
  end

  def xhr_add_invoice
    if request.get?
      invoice = Invoice.new
      render partial: 'modal--add-invoice', locals: { invoice: invoice }
    elsif request.post?
      invoice = Invoice.new(invoice_params)
      if invoice.save
        render json: { invoice: invoice }
      else
        render json: {
          errors: invoice.errors.full_messages,
          status: 400
        }
      end
    end
  end

  def destroy
    @invoice.destroy!

    redirect_to invoices_path, notice: "Invoice for #{@invoice.client_name} successfully destroyed."
  end

  def xhr_change_client_name
    if request.get?
      render partial: 'modal--change-client-name', locals: { invoice: @invoice }
    elsif request.patch?
      @invoice.client_name = params[:invoice][:client_name]
      if @invoice.save
        render json: { id: @invoice.id, client_name: @invoice.client_name }
      else
        render json: @invoice.errors.full_messages.first
      end
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:amount, :client_name, :tax)
  end

  def find_invoice
    @invoice = Invoice.find params[:id]
  end
end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_action :find_invoice, only: %w[index xhr_add_purchase_order edit update destroy]
  before_action :find_purchase_order, only: %w[destroy edit update]

  def index
    @purchase_orders = @invoice.purchase_orders
  end

  def xhr_add_purchase_order
    if request.get?
      purchase_order = @invoice.purchase_orders.new
      render partial: 'modal--add-purchase-order', locals: { invoice: @invoice, purchase_order: purchase_order }
    elsif request.post?
      purchase_order = @invoice.purchase_orders.new(purchase_order_params)
      if purchase_order.save
        render_success(edit_invoice_purchase_order_path(@invoice.id, purchase_order.id))
      else
        render_error(purchase_order.errors.full_messages)
      end
    end
  end

  def edit; end

  def update
    if @purchase_order.update(purchase_order_params)
      render_success(invoice_purchase_orders_path(@invoice))
    else
      render_error(@purchase_order.errors.full_messages)
    end
  end

  def destroy
    @purchase_order.destroy!

    redirect_to invoice_purchase_orders_path(@invoice),
                notice: "PurchaseOrder for #{@purchase_order.client_name} successfully destroyed."
  end

  private

  def purchase_order_params
    params.require(:purchase_order).permit(:amount, :client_name, :tax, :vendor, :status)
  end

  def find_invoice
    @invoice = Invoice.find params[:invoice_id]
  end

  def find_purchase_order
    @purchase_order = PurchaseOrder.find params[:id]
  end

  # TODO: These methods should be a part of concern
  def render_success(location)
    render json: { location: location, status: 200 }
  end

  def render_error(errors)
    render json: { errors: errors, status: 400 }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_invoice.html.erb
<tr class="invoices-table__item-tr" data-id="<%= invoice.id %>">
  <td class="invoices-table__item-td invoices-table__item-td--client-name"><%= invoice.client_name %></td>
  <td class="invoices-table__item-td"><%= number_to_currency invoice.amount %></td>
  <td class="invoices-table__item-td"><%= invoice.tax %></td>
  <td class="invoices-table__item-td"><%= number_to_currency invoice.total %></td>
  <td class="invoices-table__item-td invoices-table__item-td--actions">
    <%= link_to '', xhr_change_client_name_invoice_path(invoice), class: 'invoice-action invoice-action--edit-name', rel: 'modal:ajax-open', title: 'Change name' %>
    <%= link_to '', xhr_add_purchase_order_invoice_purchase_orders_path(invoice), class: 'purchase-action purchase-action--add-purchase', rel: 'modal:ajax-open', title: 'Add Purchase Order' %>
    <%= link_to '', invoice_path(invoice), method: :delete, class: 'invoice-action invoice-action--delete', title: 'Delete invoice' %>
  </td>
</tr>

app/views/invoices/_modal--add-invoice.html.erb
<div class="modal modal--add-invoice">
  <div class="modal__header">
    Add Invoice
  </div>
  <%= form_with model: invoice, url: xhr_add_invoice_invoices_path, class: 'modal__form' do |f| %>
    <div class="form-group">
      <label class="control-label">Client Name</label>
      <div>
        <%= f.text_field :client_name, class: 'field field--client-name form-control input-lg' %>
      </div>
      <div class="error-message error-message--client-name"></div>
    </div>
    <div class="form-group">
      <label class="control-label">Amount</label>
      <div>
        <%= f.text_field :amount, class: 'field field--amount form-control input-lg' %>
      </div>
      <div class="error-message error-message--amount"></div>
    </div>
    <div class="form-group">
      <label class="control-label">Tax</label>
      <div>
        <%= f.text_field :tax, class: 'field field--tax form-control input-lg' %>
      </div>
      <div class="error-message error-message--tax"></div>
    </div>
    <div class="modal__buttons-container">
      <button class="p-button">Add</button>
    </div>
  <% end %>
</div>

app/views/invoices/_modal--change-client-name.html.erb
<div class="modal modal--change-client-name">
  <div class="modal__header">
    Change Client Name
  </div>
  <%= form_with model: invoice, url: xhr_change_client_name_invoice_path(invoice), class: 'modal__form' do |f| %>
    <%= f.text_field :client_name, class: 'field field--client-name' %>
    <div class="error-message error-message--client-name"></div>

    <div class="modal__buttons-container">
      <button class="p-button">Change</button>
    </div>
  <% end %>
</div>

app/views/invoices/index.html.erb
<div class="float-right">
  <%= link_to '', xhr_add_invoice_invoices_path, class: 'invoice-action invoice-action--add-invoice', rel: 'modal:ajax-open', title: 'Add Invoice' %>
</div>
<table class="invoices-table">
  <thead>
    <tr>
      <th class="invoices-table__header invoices-table__header--sortable">
        Client Name
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Amount
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Tax
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Total
      </th>
      <th class="invoices-table__header"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'invoice', collection: @invoices  %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200italic,300,400,600,700,400italic,600italic,700italic',
      '/assets/css/application.css'
    %>
  </head>

  <body>
    <header class="header header--sticky">

    </header>

    <main class="main">
      <% flash.each do |type, message| %>
        <div class="flash flash--<%= type %>">
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
    </main>

    <%= javascript_include_tag '//code.jquery.com/jquery-3.1.1.min.js',
      '//cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.js',
      '//cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.8.0/jquery.modal.min.js',
      '/assets/js/application.js'
    %>
  </body>
</html>

app/views/purchase_orders/_modal--add-purchase-order.html.erb
<div class="modal modal--add-purchase-order">
  <div class="modal__header">
    Add Purchase Order
  </div>
  <%= form_with model: purchase_order, url: xhr_add_purchase_order_invoice_purchase_orders_path(invoice), class: 'modal__form' do |f| %>
    <div class="form-group">
      <label class="control-label">Client Name</label>
      <div>
        <%= f.text_field :client_name, class: 'field field--client-name form-control input-lg', value: invoice.client_name %>
      </div>
      <div class="error-message error-message--client-name"></div>
    </div>
    <div class="form-group">
      <label class="control-label">Amount</label>
      <div>
        <%= f.text_field :amount, class: 'field field--amount form-control input-lg', value: invoice.amount %>
      </div>
      <div class="error-message error-message--amount"></div>
    </div>
    <div class="form-group">
      <label class="control-label">Tax</label>
      <div>
        <%= f.text_field :tax, class: 'field field--tax form-control input-lg', value: invoice.tax %>
      </div>
      <div class="error-message error-message--tax"></div>
    </div>
    <div class="form-group">
      <label class="control-label">Vendor</label>
      <div>
        <%= f.text_field :vendor, class: 'field field--vendor form-control input-lg' %>
      </div>
      <div class="error-message error-message--vendor"></div>
    </div>
    <div class="form-group">
      <label class="control-label">Status</label>
      <div>
        <%= f.select :status, options_for_select(%i[draft paid delivered]), {:include_blank => 'Please Select'}, {class: 'field field--status form-control input-lg'} %>
      </div>
      <div class="error-message error-message--status"></div>
    </div>
    <div class="modal__buttons-container">
      <button class="p-button">Add</button>
    </div>
  <% end %>
</div>

app/views/purchase_orders/_purchase_order.html.erb
<tr class="purchase-table__item-tr" data-id="<%= purchase_order.id %>">
  <td class="purchase-table__item-td purchase-table__item-td--client-name"><%= purchase_order.client_name %></td>
  <td class="purchase-table__item-td"><%= number_to_currency purchase_order.amount %></td>
  <td class="purchase-table__item-td"><%= purchase_order.tax %></td>
  <td class="purchase-table__item-td"><%= number_to_currency purchase_order.total %></td>
  <td class="purchase-table__item-td"><%= purchase_order.vendor %></td>
  <td class="purchase-table__item-td"><%= purchase_order.status %></td>
  <td class="purchase-table__item-td purchase-table__item-td--actions">
    <%= link_to '', edit_invoice_purchase_order_path(@invoice, purchase_order), class: 'purchase-action purchase-action--edit-name', title: 'Update Purchase Order' %>
    <%= link_to '', invoice_purchase_order_path(@invoice, purchase_order), method: :delete, class: 'purchase-action purchase-action--delete', title: 'Delete invoice' %>
  </td>
</tr>

app/views/purchase_orders/edit.html.erb
<div class="d-ruby-text">
  <%= link_to '', invoice_purchase_orders_path(@invoice), class: 'purchase-action purchase-action--back', title: 'Back To Purchase Orders' %>
  <h1>Edit Purchase Order</h1>
</div>
<%= form_with model: @purchase_order, url: invoice_purchase_order_path(@invoice, @purchase_order), class: 'purchase-order-form' do |f| %>
  <div class="form-group">
    <label class="control-label">Client Name</label>
    <div>
      <%= f.text_field :client_name, class: 'field field--client-name form-control input-lg' %>
    </div>
    <div class="error-message error-message--client-name"></div>
  </div>
  <div class="form-group">
    <label class="control-label">Amount</label>
    <div>
      <%= f.text_field :amount, class: 'field field--amount form-control input-lg' %>
    </div>
    <div class="error-message error-message--amount"></div>
  </div>
  <div class="form-group">
    <label class="control-label">Tax</label>
    <div>
      <%= f.text_field :tax, class: 'field field--tax form-control input-lg' %>
    </div>
    <div class="error-message error-message--tax"></div>
  </div>
  <div class="form-group">
    <label class="control-label">Vendor</label>
    <div>
      <%= f.text_field :vendor, class: 'field field--vendor form-control input-lg' %>
    </div>
    <div class="error-message error-message--vendor"></div>
  </div>
  <div class="form-group">
    <label class="control-label">Status</label>
    <div>
      <%= f.select :status, options_for_select(%i[draft paid delivered], @purchase_order.status), {:include_blank => 'Please Select'}, {class: 'field field--status form-control input-lg'} %>
    </div>
    <div class="error-message error-message--status"></div>
  </div>
  <div class="modal__buttons-container">
    <button class="p-button">Update</button>
  </div>
<% end %>

app/views/purchase_orders/index.html.erb
<%= link_to '', invoices_path, class: 'purchase-action purchase-action--back', title: 'Back To Invoice' %>
<table class="purchase-table">
  <thead>
    <tr>
      <th class="purchase-table__header purchase-table__header--sortable">
        Client Name
      </th>
      <th class="purchase-table__header purchase-table__header--sortable">
        Amount
      </th>
      <th class="purchase-table__header purchase-table__header--sortable">
        Tax
      </th>
      <th class="purchase-table__header purchase-table__header--sortable">
        Total
      </th>
      <th class="purchase-table__header purchase-table__header--sortable">
        Vendor
      </th>
      <th class="purchase-table__header purchase-table__header--sortable">
        Status
      </th>
      <th class="purchase-table__header"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'purchase_order', collection: @purchase_orders %>
    <% unless @purchase_orders.present? %>
      <tr class="purchase-table__item-tr">
        <td class="purchase-table__item-td text-center" colspan="7">No purchase order available</td>
      </tr>
    <% end %>
  </tbody>
</table>